name: salesforce ci
on: 
  pull_request:
    branches:
      - integration

jobs:
  deploy_to_sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Make temporary directory
        run: |
          mkdir ./temp

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ./temp/sfdx-cli
          tar xJf sfdx-linux-x64.tar.xz -C ./temp/sfdx-cli --strip-components 1
          echo "./temp/sfdx-cli/bin" >> $GITHUB_PATH
      - name: Display sfdx version
        run: sfdx version

      # Save into private-key
      - name: Save into private-key
        run: echo -n ${{ secrets.PRIVATE_KEY_BASE64ED }} | base64 -d > ./temp/server.key

      # Authenticate to access the sandbox
      - name: Authenticate to access the sandbox
        run: sfdx force:auth:jwt:grant --instanceurl=https://test.salesforce.com/ --jwtkeyfile ./temp/server.key --username ${{ secrets.ORG_USER }} --clientid ${{ secrets.CLIENT_ID }}